services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    healthcheck:
      test: bash -c "pg_isready -U postgres -d postgres"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - backend

  person_service:
    image: backend:latest
    build:
      context: .
      dockerfile: ./backend.dockerfile
      target: release
    container_name: person
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    command: "/app/bin/lab_01"
    ports:
      - 8080:6543

networks:
  backend:
    driver: bridge
